---
sudo: false
language: go
go:
  - 1.11.1
git:
  depth: 1
env:
  - GO111MODULE=on
install:
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
script:
  - make test
  - make cover
  - ${GOPATH}/bin/goveralls -coverprofile=coverage-all.out -service=travis-ci
